# Generated by Django 4.2.5 on 2023-10-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_blog_thumbnail_alter_post_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
