# Generated by Django 4.2.5 on 2023-10-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
